// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedicaiFacility.BusinessObject;

public partial class Appointment
{
    public int AppointmentId { get; set; }

    public int? PatientId { get; set; }

    public int? ExpertId { get; set; }

    public int? FacilityId { get; set; }

    public DateTime AppointmentDate { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual MedicalExpert Expert { get; set; }

    public virtual MedicalFacility Facility { get; set; }

    public virtual MedicalHistory MedicalHistory { get; set; }

    public virtual Patient Patient { get; set; }

    public virtual ICollection<RatingsAndFeedback> RatingsAndFeedbacks { get; set; } = new List<RatingsAndFeedback>();

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}