// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedicaiFacility.BusinessObject;

public partial class Conversation
{
    public int ConversationId { get; set; }

    public int? PatientId { get; set; }

    public int? AdminId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User Admin { get; set; }

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();

    public virtual User Patient { get; set; }
}