// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedicaiFacility.BusinessObject;

public partial class Disease
{
    public int DiseaseId { get; set; }

    public string DiseaseName { get; set; }

    public string Symptoms { get; set; }

    public string Description { get; set; }

    public bool? IsActive { get; set; }

    public int? DepartmentId { get; set; }

    public virtual Department Department { get; set; }

    public virtual ICollection<HealthRecordDisease> HealthRecordDiseases { get; set; } = new List<HealthRecordDisease>();
}