// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedicaiFacility.BusinessObject;

public partial class FacilityDepartment
{
    public int FacilityDepartmentId { get; set; }

    public int? FacilityId { get; set; }

    public int? DepartmentId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public bool? Status { get; set; }

    public virtual Department Department { get; set; }

    public virtual MedicalFacility Facility { get; set; }
}