// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedicaiFacility.BusinessObject;

public partial class HealthRecord
{
    public int RecordId { get; set; }

    public int? PatientId { get; set; }

    public int? UploadedBy { get; set; }

    public string FileName { get; set; }

    public string FilePath { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string SharedLink { get; set; }

    public int? DiseaseId { get; set; }

    public virtual Disease Disease { get; set; }

    public virtual Patient Patient { get; set; }

    public virtual MedicalExpert UploadedByNavigation { get; set; }
}