// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedicaiFacility.BusinessObject;

public partial class HealthRecordDisease
{
    public int HealthRecordDiseaseId { get; set; }

    public int? RecordId { get; set; }

    public int? DiseaseId { get; set; }

    public virtual Disease Disease { get; set; }

    public virtual HealthRecord Record { get; set; }
}