// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedicaiFacility.BusinessObject;

public partial class MedicalFacility
{
    public int FacilityId { get; set; }

    public string FacilityName { get; set; }

    public string Address { get; set; }

    public string Service { get; set; }

    public string FacilityType { get; set; }

    public bool? Verified { get; set; }

    public string ContactInfo { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual ICollection<FacilityDepartment> FacilityDepartments { get; set; } = new List<FacilityDepartment>();

    public virtual ICollection<MedicalExpert> MedicalExperts { get; set; } = new List<MedicalExpert>();
}