// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedicaiFacility.BusinessObject;

public partial class MedicalExpert
{
    public int ExpertId { get; set; }

    public int? UserId { get; set; }

    public string Specialization { get; set; }

    public int ExperienceYears { get; set; }

    public string Department { get; set; }

    public string Schedule { get; set; }

    public decimal? PriceBooking { get; set; }

    public int? FacilityId { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual MedicalFacility Facility { get; set; }

    public virtual ICollection<HealthArticle> HealthArticles { get; set; } = new List<HealthArticle>();

    public virtual ICollection<HealthRecord> HealthRecords { get; set; } = new List<HealthRecord>();

    public virtual ICollection<MedicalExpertSchedule> MedicalExpertSchedules { get; set; } = new List<MedicalExpertSchedule>();

    public virtual User User { get; set; }
}