// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedicaiFacility.BusinessObject;

public partial class MedicalExpertSchedule
{
    public int ScheduleId { get; set; }

    public int? ExpertId { get; set; }

    public string DayOfWeek { get; set; }

    public virtual MedicalExpert Expert { get; set; }
}