// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedicaiFacility.BusinessObject;

public partial class MedicalExpert
{
    public int ExpertId { get; set; }

    public string Specialization { get; set; }

    public int ExperienceYears { get; set; }

    public string Department { get; set; }

    public decimal? PriceBooking { get; set; }

    public int? StartHour { get; set; }

    public int? EndHour { get; set; }

    public int? FacilityId { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual User Expert { get; set; }

    public virtual MedicalFacility Facility { get; set; }

    public virtual ICollection<MedicalExpertSchedule> MedicalExpertSchedules { get; set; } = new List<MedicalExpertSchedule>();
}