// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedicaiFacility.BusinessObject;

public partial class MedicalHistory
{
    public int HistoryId { get; set; }

    public int? AppointmentId { get; set; }

    public string Diagnosis { get; set; }

    public string Treatment { get; set; }

    public string Prescription { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Appointment Appointment { get; set; }
}