// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedicaiFacility.BusinessObject;

public partial class RatingsAndFeedback
{
    public int FeedbackId { get; set; }

    public int? AppointmentId { get; set; }

    public int Rating { get; set; }

    public string Feedback { get; set; }

    public DateTime? CreatedAt { get; set; }

    public bool? IsActive { get; set; }

    public virtual Appointment Appointment { get; set; }
}