// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MedicaiFacility.BusinessObject;

public partial class SystemBalance
{
    public int BalanceId { get; set; }

    public decimal TotalBalance { get; set; }

    public string BankAccount { get; set; }

    public DateTime? LastUpdated { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}