name: .NET 8.0 CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Publish
      run: dotnet publish --configuration Release --no-build --output ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-artifact
        path: ./publish/

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: app-artifact
        path: ./publish

    - name: Deploy to DigitalOcean
      run: |
        # Sử dụng SSH với username và password cho DigitalOcean
        echo "Deploying to $DIGITALOCEAN_HOST..."
        scp -r ./publish/* $DIGITALOCEAN_USERNAME@$DIGITALOCEAN_HOST:/path/to/deploy
      env:
        DIGITALOCEAN_HOST: ${{ secrets.DIGITALOCEAN_HOST }}
        DIGITALOCEAN_USERNAME: ${{ secrets.DIGITALOCEAN_USERNAME }}
        DIGITALOCEAN_PASSWORD: ${{ secrets.DIGITALOCEAN_PASSWORD }}

    - name: Run deployment script
      run: sshpass -p "$DIGITALOCEAN_PASSWORD" ssh $DIGITALOCEAN_USERNAME@$DIGITALOCEAN_HOST "cd /path/to/deploy && ./deploy.sh"
      env:
        DIGITALOCEAN_HOST: ${{ secrets.DIGITALOCEAN_HOST }}
        DIGITALOCEAN_USERNAME: ${{ secrets.DIGITALOCEAN_USERNAME }}
        DIGITALOCEAN_PASSWORD: ${{ secrets.DIGITALOCEAN_PASSWORD }}
